name: Clone Repository

description: Clones a repository if not already present.

inputs:
    repo_url:
        description: "The URL of the repository to clone"
        required: true
    repo_dir:
        description: "The directory name where the repository should be cloned"
        required: true

runs:
    using: "composite"
    steps:
        - run: |
              if [ ! -d "${{ inputs.repo_dir }}" ]; then
                echo "Cloning repository ${{ inputs.repo_url }} into directory ${{ inputs.repo_dir }}..."
                git clone ${{ inputs.repo_url }} ${{ inputs.repo_dir }}
              else
                echo "Directory ${{ inputs.repo_dir }} already exists, skipping clone."
              fi
          shell: bash
